# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
source:           ./flatstrap/docs/
destination:      ./_gh_pages
host:             0.0.0.0
port:             9001
baseurl:          roachhd.github.io/flatstrap/
url:              http://localhost:9001
encoding:         UTF-8

exclude:
  - "jade"
  - "vendor"

# Custom vars
current_version:  3.1.1
repo:             https://github.com/roachhd/flatstrap
sass_repo:        https://github.com/roachhd/flatstrap

download:
  source:         https://github.com/roachhd/flatstrap/archive/v3.1.1.zip
  dist:           https://github.com/roachhd/flatstrap/archive/v3.1.1.zip
  sass:           https://github.com/roachhd/flatstrap/archive/v3.1.1.zip

blog:             http://katieball.me/notepad
expo:             http://expo.getbootstrap.com

cdn:
  css:            //netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css
  css_theme:      //netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css
  js:             //netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js
